### ISSUE TITLE
docker-compose down && docker-compose up出现报错

### ISSUE THREAD

**Issue by XUxuliang** [AlexGeControl/Sensor-Fusion-for-Localization-Courseware#11]
通过clone新的github上面的工程，再新的下载根目录中查看运行的容器显示没有
itcast@ubuntu:~/Sensor-Fusion-for-Localization-Courseware$ docker ps
CONTAINER ID   IMAGE     COMMAND   CREATED   STATUS    PORTS     NAMES
执行docker-compose down && docker-compose up报错如下
itcast@ubuntu:~/Sensor-Fusion-for-Localization-Courseware$ docker-compose down && docker-compose up
Removing network sensor-fusion-for-localization-courseware_default
Creating network "sensor-fusion-for-localization-courseware_default" with the default driver
Creating sensor-fusion-workspace-cpu ... error

ERROR: for sensor-fusion-workspace-cpu  Cannot create container for service workspace-bionic-cpu-vnc: Conflict. The container name "/sensor-fusion-workspace-cpu" is already in use by container "934ce78a200990466c077e2c186a3f39b7a8e275d9caed8f0149cc80d920cc4f". You have to remove (or rename) that container to be able to reuse that name.

ERROR: for workspace-bionic-cpu-vnc  Cannot create container for service workspace-bionic-cpu-vnc: Conflict. The container name "/sensor-fusion-workspace-cpu" is already in use by container "934ce78a200990466c077e2c186a3f39b7a8e275d9caed8f0149cc80d920cc4f". You have to remove (or rename) that container to be able to reuse that name.
ERROR: Encountered errors while bringing up the project.
请问老师这个怎么处理？

**Comment by AlexGeControl** [comment]
和repo没有关系，自己在google上搜索错误信息吧

**Comment by XUxuliang** [comment]
好的，老师，以解决，这是与第一章的容器冲突 的问题，把所有的容器删除就可以解决
