### ISSUE TITLE
this is a bug: it should be "Eigen::VectorXd" 

### ISSUE THREAD

**Issue by ZLiu45** [AlexGeControl/Sensor-Fusion-for-Localization-Courseware#12]
https://github.com/AlexGeControl/Sensor-Fusion-for-Localization-Courseware/blob/24bd9e9bb30a29324ffc206fda425ba7a4fbe871/workspace/assignments/02-lidar-odometry-basic/src/lidar_localization/include/lidar_localization/models/registration/sicp/ICP.h#L367

**Comment by AlexGeControl** [comment]
这个文件取自github作者得实现，是readonly lib，且在我的参考答案里没有报错
