### ISSUE TITLE
evo运行报错

### ISSUE THREAD

**Issue by XUxuliang** [AlexGeControl/Sensor-Fusion-for-Localization-Courseware#13]
<img width="468" alt="1212312" src="https://user-images.githubusercontent.com/96403117/147355866-4d271349-2934-47d8-a2ac-7a7bdc642fc5.png">
老师，请问这个问题怎么解决呀？在主机和docker上都不行

**Comment by AlexGeControl** [comment]
我猜是你输入的数据有问题，数据本身有nan，才会导致工具计算出问题. 你先看看输入的轨迹是否正常
