### ISSUE TITLE
第二章运行运行程序时，出现如下报错

### ISSUE THREAD

**Issue by XUxuliang** [AlexGeControl/Sensor-Fusion-for-Localization-Courseware#14]
<img width="443" alt="23123" src="https://user-images.githubusercontent.com/96403117/147356030-e8f0f2d5-1354-4e8f-8c62-989abc37145c.png">
老师，这个问题是否有影响，这是为什么呢？

**Comment by AlexGeControl** [comment]
你的config里面用的是sicp，且todo都没有填写的吧，这个必须要补完todo才能用
