### ISSUE TITLE
#第二章代码# 运行结束时使用rosservice call /save_map 报错,如何解决？

### ISSUE THREAD

**Issue by coldrainy** [AlexGeControl/Sensor-Fusion-for-Localization-Courseware#15]
**Screenshots**
![Screenshot from 2021-12-25 10-50-26](https://user-images.githubusercontent.com/20240108/147376371-ae401a60-e6c0-403d-96a0-3b7dc1bbc03f.png)
![Screenshot from 2021-12-25 10-52-47](https://user-images.githubusercontent.com/20240108/147376393-d3b16d2c-762a-47aa-9e96-768bbe8e8236.png)

**Comment by AlexGeControl** [comment]
你没有source，建议查资料，理解ros那个source在做什么

**Comment by coldrainy** [comment]
来信收到，谢谢！
