### ISSUE TITLE
[docker启动报错]-[WEEK1]-[更换了docker根目录的名称，docker启动报错]

### ISSUE THREAD

**Issue by shuttworth** [AlexGeControl/Sensor-Fusion-for-Localization-Courseware#2]
**Describe the bug**
给repo名称前加了一个01序号，然后原来的docker就无法启动了，报了如下的错误，请问如何解决？

**Screenshots**
![docker启动问题截图1](https://user-images.githubusercontent.com/46838923/146708605-b32f477a-e756-4b1a-8de7-da3e0181b716.png)

**Comment by shuttworth** [comment]
解决了，先查看docker环境，把这个docker的ID删掉，再重新执行docker启动的命令就可以了

**Comment by AlexGeControl** [comment]
行，其实不用加这个序号的，所有的作业共用同一个Docker环境. 直接按照repo的结构, 做作业时切换分支即可.
