### ISSUE TITLE
第一章中网页上的虚拟机，显示不对

### ISSUE THREAD

**Issue by XUxuliang** [AlexGeControl/Sensor-Fusion-for-Localization-Courseware#4]
文档说配置参数，查一圈还是不知道怎么配置，想让这个分辨率改一下

**Comment by AlexGeControl** [comment]
基础分辨率已经固定至1920-by-1080. 原因在于web vnc配置了auto-scaling. 此处不再进行修改. 如果需要的话，自行修改docker/image/etc/supervisor/conf.d/lxde.conf中的分辨率1920x1200x16和相关vnc启动命令吧.

**Comment by XUxuliang** [comment]
老师，我的docker/image/etc/supervisor/conf.d/lxde.conf中的分辨率是这个1920x1200x16呀，需要修改成别的嘛？

**Comment by AlexGeControl** [comment]
> 老师，我的docker/image/etc/supervisor/conf.d/lxde.conf中的分辨率是这个1920x1200x16呀，需要修改成别的嘛？

我建议你最好不折腾了，这个分辨率是足够的。

非要自己折腾，仅仅修改repo中的文件不会对镜像有任何影响. 真要做，你需要细读docker文件下环境的定义, 自己修改启动文件，然后重新编译. 编译时最好有高速vpn, 否则依赖下载会需要很长的时间. 

同时你还需要了解novnc, 也就是这个浏览器版本vnc是怎么工作的, 因为最终浏览器呈现的桌面，还经由novnc做了转发.

感兴趣自己研究docker文件夹下的环境定义吧，但这门课的重点还是后面的算法，和ROS c++框架.

**Comment by XUxuliang** [comment]
好的，老师，就是感觉人家的都正常显示，就我的不正常，感觉自己哪里做错了~谢谢老师指点~
