### ISSUE TITLE
代码编译

### ISSUE THREAD

**Issue by dlutjwh** [AlexGeControl/Sensor-Fusion-for-Localization-Courseware#5]
老师好，我把#include "lidar_localization/models/registration/sicp/ICP.h"  从 scip_registration.cpp移动到 scip_registration.hpp下，编译时产生多次定义的错误 ，需要注释掉ICP.h中的  IWICP 的命名空间才能通过，是只有我电脑有这个问题吗（虽然并不影响结果），谢谢老师。

**Comment by AlexGeControl** [comment]
暂时看不出来哪里有问题

从设计角度：icp.h是SICP作者的开源实现，等效于一个lib，sicp-registration是框架真正的接口，所以sicp-registration.hpp中不应该暴露icp.h的实现，否则你改动icp.h中的实现，整个库都要重新编译

工程角度: 我还不清楚你改了什么，如果你要动框架结构，最好先理解清楚目前框架的设计，同时确保include文件的保护，cmake编译规则，都修改正确了，否则就用我默认的
