### ISSUE TITLE
[雷达运动补偿图示的理解]-[WEEK02]

### ISSUE THREAD

**Issue by shuttworth** [AlexGeControl/Sensor-Fusion-for-Localization-Courseware#6]
**Describe the bug**
关于雷达运动补偿的公式图示理解
![image](https://user-images.githubusercontent.com/46838923/146781048-831a954e-4ce9-4838-bdec-4758930e6808.png)
我画了个图，黑色线代表T0 Ti Pi在世界系下的含义，红色线代表对上图红色框里公式的理解
![image](https://user-images.githubusercontent.com/46838923/146781145-222a1a7f-9c22-43c3-9fb8-cef951f94bba.png)

请问T0 Ti Pi含义的理解是否正确？公式推导的理解是否正确？

**Comment by AlexGeControl** [comment]
对

如果对坐标系和李代数还有参考需要，推荐去翻一下State Estimation for Robotics传感器章节和李代数章节，第二章仅仅是一系列数学的开端
