### ISSUE TITLE
icp_svd

### ISSUE THREAD

**Issue by dlutjwh** [AlexGeControl/Sensor-Fusion-for-Localization-Courseware#9]
老师，请问自己实现的icp_svd轨迹前面还正常，后面尺度就越飘越大，有什么解决办法么？
![svd](https://user-images.githubusercontent.com/40100470/147043356-6abbd7ad-0f5c-409d-a98f-ab56b9a9e56a.png)

**Comment by AlexGeControl** [comment]
这个是正常的，前端是迭代计算，随着时间的增长，数值误差的不断累积一定会把结果带偏. 这个是system error，不可消除，算法再怎么优化，也只能减缓发散的速度. 真能解决, 后面的就都不用学了

解决方案就是继续往后学习，靠回环检测，卡尔曼滤波的online estimation，图优化和滑动窗口的batch optimization等方法，来"平差"，推荐可以去翻翻高博的视觉slam14讲
